[package]
name                    = "executor-resource-handles"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true

keywords.workspace      = true
categories.workspace    = true
homepage.workspace      = true
repository.workspace    = true

[dependencies]
# store.workspace         = true
task_executor.workspace = true
workunit_store.workspace = true
once_cell.workspace     = true

[dev-dependencies]
tokio                   = { workspace = true, features = ["macros"] }
